package com.sachin.example.simplegroovydsl.model;

import java.util.Date;

/**
 * Database Table Remarks:
 *   dsl配置历史记录表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table T_dsl_config_history
 */
public class DslConfigHistoryEntity {
    /**
     * Database Column Remarks:
     *   PK
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_dsl_config_history.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   记录创建的物理时间戳
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_dsl_config_history.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * Database Column Remarks:
     *   记录修改的物理时间戳
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_dsl_config_history.gmt_modify
     *
     * @mbg.generated
     */
    private Date gmtModify;

    /**
     * Database Column Remarks:
     *   dsl名称编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_dsl_config_history.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   dsl配置内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_dsl_config_history.config
     *
     * @mbg.generated
     */
    private String config;

    /**
     * Database Column Remarks:
     *   操作人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_dsl_config_history.operator
     *
     * @mbg.generated
     */
    private String operator;

    /**
     * Database Column Remarks:
     *   版本号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_dsl_config_history.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     * Database Column Remarks:
     *   操作类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_dsl_config_history.op_type
     *
     * @mbg.generated
     */
    private String opType;

    /**
     * Database Column Remarks:
     *   操作描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_dsl_config_history.describe
     *
     * @mbg.generated
     */
    private String describe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_dsl_config_history.id
     *
     * @return the value of T_dsl_config_history.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_dsl_config_history.id
     *
     * @param id the value for T_dsl_config_history.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_dsl_config_history.gmt_create
     *
     * @return the value of T_dsl_config_history.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_dsl_config_history.gmt_create
     *
     * @param gmtCreate the value for T_dsl_config_history.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_dsl_config_history.gmt_modify
     *
     * @return the value of T_dsl_config_history.gmt_modify
     *
     * @mbg.generated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_dsl_config_history.gmt_modify
     *
     * @param gmtModify the value for T_dsl_config_history.gmt_modify
     *
     * @mbg.generated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_dsl_config_history.name
     *
     * @return the value of T_dsl_config_history.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_dsl_config_history.name
     *
     * @param name the value for T_dsl_config_history.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_dsl_config_history.config
     *
     * @return the value of T_dsl_config_history.config
     *
     * @mbg.generated
     */
    public String getConfig() {
        return config;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_dsl_config_history.config
     *
     * @param config the value for T_dsl_config_history.config
     *
     * @mbg.generated
     */
    public void setConfig(String config) {
        this.config = config;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_dsl_config_history.operator
     *
     * @return the value of T_dsl_config_history.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_dsl_config_history.operator
     *
     * @param operator the value for T_dsl_config_history.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_dsl_config_history.version
     *
     * @return the value of T_dsl_config_history.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_dsl_config_history.version
     *
     * @param version the value for T_dsl_config_history.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_dsl_config_history.op_type
     *
     * @return the value of T_dsl_config_history.op_type
     *
     * @mbg.generated
     */
    public String getOpType() {
        return opType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_dsl_config_history.op_type
     *
     * @param opType the value for T_dsl_config_history.op_type
     *
     * @mbg.generated
     */
    public void setOpType(String opType) {
        this.opType = opType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_dsl_config_history.describe
     *
     * @return the value of T_dsl_config_history.describe
     *
     * @mbg.generated
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_dsl_config_history.describe
     *
     * @param describe the value for T_dsl_config_history.describe
     *
     * @mbg.generated
     */
    public void setDescribe(String describe) {
        this.describe = describe;
    }
}